//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSSIER_ADMISSION
    {
        public int ID_ADMISSION { get; set; }
        public Nullable<bool> CHIRURGIE_PROGRAMME { get; set; }
        public System.DateTime DATE_ADMISSION { get; set; }
        public Nullable<System.DateTime> DATE_CHIRURGIE { get; set; }
        public Nullable<System.DateTime> DATE_CONGE { get; set; }
        public string NAM { get; set; }
        public Nullable<int> NUMERO_LIT { get; set; }
        public Nullable<int> ID_MEDECIN { get; set; }
    
        public virtual MEDECIN MEDECIN { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        public virtual LIT LIT { get; set; }
    }
}
