//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIT()
        {
            this.DOSSIER_ADMISSION = new HashSet<DOSSIER_ADMISSION>();
        }
    
        public int NUMERO_LIT { get; set; }
        public bool LIT_OCCUPE { get; set; }
        public Nullable<int> NUMERO_TYPE { get; set; }
        public Nullable<int> ID_DEPARTEMENT { get; set; }
    
        public virtual DEPARTEMENT DEPARTEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOSSIER_ADMISSION> DOSSIER_ADMISSION { get; set; }
        public virtual TYPE_LIT TYPE_LIT { get; set; }
    }
}
