//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDECIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDECIN()
        {
            this.DOSSIER_ADMISSION = new HashSet<DOSSIER_ADMISSION>();
        }
    
        public int ID_MEDECIN { get; set; }
        public string NOM_MEDECIN { get; set; }
        public string PRENOM_MEDECIN { get; set; }
        public string SPECIALITE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOSSIER_ADMISSION> DOSSIER_ADMISSION { get; set; }
    }
}
