//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARENT()
        {
            this.PATIENTs = new HashSet<PATIENT>();
        }
    
        public int ref_parent { get; set; }
        public string nom_PARENT { get; set; }
        public string PRENOM_PARENT { get; set; }
        public string ADRESSE_PARENT { get; set; }
        public string VILLE_PARENT { get; set; }
        public string PROVINCE_PARENT { get; set; }
        public string CODE_POSTAL_PARENT { get; set; }
        public string TELEPHONE_PARENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT> PATIENTs { get; set; }
    }
}
